# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jasmine Angle
title_suffix: Jasmine Angle's Personal Website
email: not-my-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  NVIDIA ASIC Engineer; UC Berkeley EECS alum; loves making chips.
description_html: >- # this means to ignore newlines until "baseurl:"
  <nobr>NVIDIA ASIC Engineer;&nbsp;</nobr><wbr><nobr>UC Berkeley EECS alum;&nbsp;</nobr><wbr><nobr>loves making chips.</nobr>
baseurl: "" # the subpath of your site, e.g. /blog
url_domain_only: "jasmineangle.dev"
url: "https://jasmineangle.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: o_O
github_username: jasmangle

# Build settings
remote_theme: https://github.com/bdhu/minimalist
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-minifier

logo: /assets/img/jasmine2.jpg
color-scheme: auto

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

jekyll-minifier:
  preserve_php: false                # Default: false
  remove_spaces_inside_tags: false   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: false                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  uglifier_args:
    harmony: true

sidebar_links:
  - name: Home
    icon: <i class="fa-solid fa-fw fa-home"></i>
    link: /
  - name: Coursework
    icon: <i class="fa-solid fa-fw fa-graduation-cap"></i>
    link: /coursework/
  - name: Blurbs
    icon: <i class="fa-solid fa-fw fa-splotch"></i>
    link: /blurbs/
  
sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-fw fa-linkedin"></i>
    link: https://linkedin.com/in/jasmangle
  - name: Twitter
    icon: <i class="fa-brands fa-fw fa-x-twitter"></i>
    link: https://x.com/jasmangle
  - name: Instagram
    icon: <i class="fa-brands fa-fw fa-instagram"></i>
    link: https://instagram.com/jasmangle
  - name: GitHub
    icon: <i class="fa-brands fa-fw fa-github"></i>
    link: https://github.com/jasmangle

# SEO Tag Processing Information
twitter:
  username: jasmangle
  card: summary_small_image

social:
  name: Jasmine Angle
  links:
    - https://linkedin.com/in/jasmangle
    - https://instagram.com/jasmangle
    - https://github.com/jasmangle
    - https://x.com/jasmangle
    - https://bsky.app/profile/angle.dev
    - https://orcid.org/0009-0008-0282-2629

# RSS Feed
author: jasmangle

feed:
  path: /feed.xml
  categories:
    - blurbs

locale: en_US

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
